kind: Deployment
metadata:
    annotations:
        deployment.kubernetes.io/revision: "4"
    generation: 12
    name: poll-deployment
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: poll
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: poll
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/cloud-container-g2
                                    operator: In
                                    values:
                                        - "true"
            containers:
                - image: sabaedr/poll-service:latest
                  imagePullPolicy: Always
                  name: poll
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  resources:
                      limits:
                          cpu: 100m
                          ephemeral-storage: 700M
                          memory: 200M
                      requests:
                          cpu: 100m
                          ephemeral-storage: 700M
                          memory: 200M
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            tolerations:
                - effect: NoSchedule
                  key: role
                  operator: Equal
                  value: cloud-container-g2
---
kind: Service
metadata:
    name: poll-service2
spec:
    clusterIP: 10.99.181.112
    clusterIPs:
        - 10.99.181.112
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: poll
    sessionAffinity: None
    type: ClusterIP
